In [14]:
!pip install tensorflow --quiet

In [15]:
import tensorflow as tf

tensor_known=tf.constant([1,2,3,4,5],dtype=tf.float32)
print(tensor_known.numpy())

[1. 2. 3. 4. 5.]


In [16]:
tensor_random = tf.random.normal(shape=(5,), dtype=tf.float32)
print("\nTensor with random values:")
print(tensor_random.numpy())


Tensor with random values:
[0.38614377 0.8896434  1.6498736  0.36141157 0.4035065 ]


In [17]:
tensor_added = tensor_known + 10
print("\nTensor after addition:")
print(tensor_added.numpy())



Tensor after addition:
[11. 12. 13. 14. 15.]


In [18]:
tensor_multiplied = tensor_known * 2
print("\nTensor after element-wise multiplication:")
print(tensor_multiplied.numpy())


Tensor after element-wise multiplication:
[ 2.  4.  6.  8. 10.]
